### ISSUE TITLE
Effective hard-dependency on statsd-instrument

### ISSUE THREAD

**Issue by colszowka** [ahawkins/harness#16]
First of all thanks for building this!

I've tried to add harness using the stathat adapter, but without adding the "statsd-instrument" gem into the app's Gemfile Harness crashes on startup. 

This is because in `lib/harness.rb` all the adapters are required on startup, and the statsd adapter itself requires that gem on it's first line.

This is by no means terrible, but it is not shown in the Readme. I'd suggest you either load dependencies of individual adapters when they are actually set up in the config or just add the statsd-instrument gem as an actual dependency to the gemspec.

**Comment by ahawkins** [comment]
Thanks for reporting this. I'll update the code to have the adapters require their own dependencies. I don't like bringing in more dependencies just because.
