### ISSUE TITLE
It's not clear how to setup resque to work with harness

### ISSUE THREAD

**Issue by ericallam** [ahawkins/harness#3]
It doesn't seem like harness automatically sets up `Resque.redis` and I am having a hard time figuring out the correct way to do this.  I'd like to reuse the connection harness is already making to redis.  Any guidance on this?

**Comment by ericallam** [comment]
It's also getting tricky to figure out which Resque version to use.  For example, when trying to use the latest version of Resque there is a version conflict with Harness:

```

    resque (~> 1.20.0) ruby depends on
      redis-namespace (~> 1.0.2) ruby

    harness (>= 0) ruby depends on
      redis-namespace (1.2.0)
```

**Comment by ahawkins** [comment]
@rubymaverick Harness and Resque don't need to share the same redis connection to work. Harness will not configure Resque's redis connection for you. That is outside of it's scope. IIRC, you should be able to do: 

``` ruby
Resque.redis = Harness.redis
```

Also, harness does not depend on an explicit version of redis namespace. You'll need to do a `bundle update` if you had installed harness before redis. Redis has an explicit version requirement.
